# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_GetTDewPointFromVapPres <- function(TDryBulb, VapPres, BOUNDS_Lower, BOUNDS_Upper, MAX_ITER_COUNT, TOLERANCE, inIP) {
    .Call(`_psychrolib_C_GetTDewPointFromVapPres`, TDryBulb, VapPres, BOUNDS_Lower, BOUNDS_Upper, MAX_ITER_COUNT, TOLERANCE, inIP)
}

CV_GetTDewPointFromVapPres <- function(TDryBulb, VapPres, BOUNDS_Lower, BOUNDS_Upper, MAX_ITER_COUNT, TOLERANCE, inIP) {
    .Call(`_psychrolib_CV_GetTDewPointFromVapPres`, TDryBulb, VapPres, BOUNDS_Lower, BOUNDS_Upper, MAX_ITER_COUNT, TOLERANCE, inIP)
}

C_GetTWetBulbFromHumRatio <- function(TDryBulb, TDewPoint, BoundedHumRatio, Pressure, MIN_HUM_RATIO, MAX_ITER_COUNT, TOLERANCE, inIP) {
    .Call(`_psychrolib_C_GetTWetBulbFromHumRatio`, TDryBulb, TDewPoint, BoundedHumRatio, Pressure, MIN_HUM_RATIO, MAX_ITER_COUNT, TOLERANCE, inIP)
}

CV_GetTWetBulbFromHumRatio <- function(TDryBulb, TDewPoint, BoundedHumRatio, Pressure, MIN_HUM_RATIO, MAX_ITER_COUNT, TOLERANCE, inIP) {
    .Call(`_psychrolib_CV_GetTWetBulbFromHumRatio`, TDryBulb, TDewPoint, BoundedHumRatio, Pressure, MIN_HUM_RATIO, MAX_ITER_COUNT, TOLERANCE, inIP)
}

